- _pkgdown.yml
For free search and better UI.
> Use BS5 for docs

- README.Rmd
Added the pharmaverse badge now that this package extension is live on the site.
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.
> update pharmaverse badge

- _pkgdown.yml
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.
> add ophtha

- docs/pkgdown.yml
- vignettes/advfq.Rmd
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.
> closes #73 ADVFQ documentation

- DESCRIPTION
- docs/pkgdown.yml
- inst/WORDLIST
- man/admiralophtha-package.Rd
- vignettes/adbcva.Rmd
> Updated names for #100

- docs/pkgdown.yml
- vignettes/admiralophtha.Rmd
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.
> updated the derivation, script and support part of get started

- CRAN-RELEASE
- DESCRIPTION
- docs/pkgdown.yml
- man/admiralophtha-package.Rd
> PR from `pre-release` to `main` for v.0.1.0

- CRAN-RELEASE
- cran-comments.md
> #116 Remove CRAN comments file

- README.md
- docs/pkgdown.yml
> 114 cran status@devel

- _pkgdown.yml
- docs/pkgdown.yml
> 141 searchbar@devel

- DESCRIPTION
- NEWS.md
- docs/pkgdown.yml
- man/admiralophtha-package.Rd
> Added report a bug link for #127

- NEWS.md
- docs/pkgdown.yml
- inst/WORDLIST
- inst/templates/ad_adbcva.R
> #137_adbcva_template_update@devel

- DESCRIPTION
- NEWS.md
- man/admiralophtha-package.Rd
> Chores to get package ready for release (issue #151)

- R/data.R
- README.md
> Updated readme for release schedule for issue #153

- NEWS.md
- R/derive_var_afeye.R
- man/derive_var_afeye.Rd
- tests/testthat/test-derive_var_afeye.R
> Closes #163 oeloc values@devel

- NEWS.md
- R/derive_var_afeye.R
- man/derive_var_afeye.Rd
- tests/testthat/test-derive_var_afeye.R
- vignettes/standards.Rmd
> Closes#174 

- NEWS.md
- R/convert_etdrs_to_logmar.R
- R/convert_logmar_to_etdrs.R
- inst/WORDLIST
- man/convert_etdrs_to_logmar.Rd
- man/convert_logmar_to_etdrs.Rd
> Closes #121 added references for etdrs to logmar conversion

- DESCRIPTION
> Closes #182 package version implemented

- .github/workflows/templates.yml
- inst/templates/ad_adbcva.R
- inst/templates/ad_adoe.R
- inst/templates/ad_advfq.R
!!! Please first merge this one before : https://github.com/pharmaverse/admiralci/pull/145 !!!
> 618 templates action

- DESCRIPTION
- NEWS.md
- _pkgdown.yml
> Closes #206 added new buttons to website

- NEWS.md
- R/derive_var_afeye.R
- R/derive_var_bcvacritxfl.R
- man/derive_var_afeye.Rd
- man/derive_var_bcvacritxfl.Rd
- tests/testthat/test-convert_etdrs_to_logmar.R
- tests/testthat/test-convert_logmar_to_etdrs.R
- tests/testthat/test-derive_var_afeye.R
- tests/testthat/test-derive_var_bcvacritxfl.R
- tests/testthat/test-derive_var_studyeye.R
Closes #217 
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.
> Closes #217: test coverage

- NEWS.md
- R/derive_var_bcvacritxfl.R
- R/derive_var_studyeye.R
- inst/templates/ad_adbcva.R
- inst/templates/ad_adoe.R
- inst/templates/ad_advfq.R
- vignettes/adbcva.Rmd
- vignettes/adoe.Rmd
- vignettes/advfq.Rmd
> Closes #226 updated subject keys across package

- DESCRIPTION
- inst/WORDLIST
- man/admiralophtha-package.Rd
> Closes #241: added orcids

- .github/workflows/common.yml
- DESCRIPTION
> Replace R 4.2 with R 4.3

- README.md
> Closes #250 Added release schedule for 2025

- DESCRIPTION
- NEWS.md
> Git commit for #264

- NEWS.md
- R/data.R
- inst/templates/ad_advfq.R
- man/admiralophtha_adbcva.Rd
- man/admiralophtha_adoe.Rd
- man/admiralophtha_advfq.Rd
- vignettes/advfq.Rmd
> Closes #243: added citation for VFQ to template, vignette and test dataset

- .Rbuildignore
- .lintr
- .lintr.R
- NEWS.md
- R/derive_var_bcvacritxfl.R
- tests/testthat.R
> Closes #280: update linter configs
